French Translation
TeamGalacticraft/Galacticraft pull request #142
Opened 2021-07-09 15:20 UTC by CMSEv7

Work in progress, I am taking a pause and I shall continue later. I am at line 100.

2021-07-09 15:24 UTC, vos6434 commented
Make a Draft as it is not finished.

2021-07-21 12:37 UTC, martmists-gh requested changes
Decided to suggest some small changes while this is still WIP. 
tl;dr try to be consistent with the english (not leaving out any information) while keeping the translations in the french crowdin format ([link](https://crowdin.com/translate/minecraft/9435/enus-fr?filter=basic&value=0))

2021-07-21 12:37 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/fr_ca.json
> +  "block.galacticraft.desh_ore": "Minerai de Desh",
Desh -> desh (consistency)

2021-07-21 12:37 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/fr_ca.json
> +  "block.galacticraft.mars_iron_ore": "Minerai de fer",
"... de Mars"

2021-07-21 12:37 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/fr_ca.json
> +  "block.galacticraft.moon_cheese_ore": "Minerai de fromage",
"... lunaire"

2021-07-26 21:13 UTC, CMSEv7 commented on src/main/resources/assets/galacticraft/lang/fr_ca.json
> +  "block.galacticraft.desh_ore": "Minerai de Desh",
Desh est un nom propre, il a été inventé pour le _purpose_ de Galacticraft.

2021-07-26 21:14 UTC, CMSEv7 commented on src/main/resources/assets/galacticraft/lang/fr_ca.json
> +  "block.galacticraft.desh_ore": "Minerai de Desh",
Desh est un nom propre, car il a été inventé pour Galacticraft.

2022-04-10 11:31 UTC, Yexiaowei11 commented
the Chinese translation

2022-06-23 02:40 UTC, closed without merging