Dutch Translation for Galactricraft
TeamGalacticraft/Galacticraft pull request #143
Opened 2021-07-18 02:48 UTC by Trico-Everfire

My apologies if it's a little rough, I use English more than my native language of Dutch so I have trouble with  phrasing certain words and sentences (Dutch is a worse language than English honestly.)

2021-07-21 12:30 UTC, martmists-gh requested changes
Mostly capitalization, also some fixed translations.

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "block.galacticraft.detailed_meteoric_iron_decoration_slab": "Gedetailleerde Meteorische Ijzer Decoratie Plaat",
Ijzere -> Ijzeren
Meteorische Ijzer -> Meteorische Ijzeren

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "block.galacticraft.cracked_moon_basalt_brick_slab": "Cracked Maan Basalt Bakstenen Plaat",
Cracked -> Gebarsten

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "block.galacticraft.cobbled_moon_rock_slab": "geplaveide Maan Steen Plaat",
geplaveide -> Geplaveide

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "block.galacticraft.basic_solar_panel": "Basis ZonnePaneel",
ZonnePaneel -> Zonnepaneel

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.meteoric_iron_ingot": "meteorisch Ijzerstaaf",
meteorisch -> Meteorische

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.titanium_shovel": "Titanium schop",
schop -> Schop

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.desh_shovel": "Desh schop",
schop -> Schop

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.raw_meteoric_iron": "Rauw meteorisch Ijzer",
meteorisch -> Meteorisch

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.tin_canister": "Tinne Busje",
Tinne -> Tinnen

OR

Tinne -> Blikken

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.iron_shard": "Ijzer Scherf",
Ijzer -> Ijzeren

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.solar_dust": "Zonne Stof",
Zonne Stof -> Zonnestof

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.hot_throwable_meteor_chunk": "Hete Gooibare Meteor Brok",
Gooibare -> Werpbare

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "tooltip.galacticraft.energy_remaining": "Resterende Energy: %s",
Energy -> Energie

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "ui.galacticraft.alpha_warning.content1": "Galacticraft is op did moment in ALPHA.",
did -> dit

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "ui.galacticraft.machine.status.idle": "Nietsdoend",
Ijdel would be more accurate

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "ui.galacticraft.machine.status.inactive": "inactief",
inactief -> Inactief

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "commands.galacticraft.dimensiontp.success.multiple": "Geteleporteerd %s entiteiten Naar %s",
%s entiteiten geleteporteerd naar %s

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "commands.galacticraft.gchouston.confirm": "Er, Houston, we hebben een probleem... (Gebruik deze command nogmaals om te teleporteren.)",
deze command -> deze opdracht (more consistent with vanilla)

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "commands.galacticraft.gchouston.success": "Je bent gered. Hopelijk de volgende keer meer geluk...",
de volgende keer meer geluk -> volgende keer beter

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "advancements.galacticraft.travel_moon.description": "Neem een Niveau 1 Raket Naar de Maan!",
Naar -> naar

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.legacy_music_disc_spacerace": "Muziekschijf",
Muziekschijf -> Muziekplaat (vanilla)

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "config.galacticraft.energy.machines.energy_storage_module_storage_size": "Energie opslag grote van energie opslag module",
grote -> grootte

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "item.galacticraft.shield_controller": "schild Controller",
schild -> Schild

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "block.galacticraft.dashed_light_panel": "Licht Paneel (gestreept)",
gestreept -> Gestreept

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "block.galacticraft.detailed_tin_decoration_slab": "Gedetailleerde Tinne Decoratie Plaat",
Tinne -> Blikken

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "block.galacticraft.moon_copper_ore": "Maan Koper Erts",
Koper Erts -> Kopererts

2021-07-21 12:30 UTC, martmists-gh commented on src/main/resources/assets/galacticraft/lang/nl_nl.json
> +  "block.galacticraft.moon_tin_ore": "Maan Tin Erts",
Tin Erts -> Tinerts

2021-07-21 22:15 UTC, Trico-Everfire commented
Yo, thanks for fixing it up, I am ashamed to admit that although it's my birth language, I haven't had a proper dutch conversation in text form since 2016, so some things just yeet over my head when translating, thanks for catching them mistakes.

2021-07-22 21:02 UTC, martmists-gh commented
No problem, that's what reviews are for :) It doesn't help that a lot of this stuff is really awkward to say in Dutch either way.

2022-06-23 02:40 UTC, closed without merging