feat: Adding the nasa workbench
TeamGalacticraft/Galacticraft pull request #256
Opened 2023-01-25 02:25 UTC by supersimple33

I have added the nasa workbench. To do this I have done the following:

- Added and registered the NASA workbench block and gave it a crafting recipe.
- Built on the `NasaWorkbenchBlock` to handle being opened and sending the user to the correct menu screens
- Create a class structuring for the Menus of the device
  - The `AbstractNasaWorkbenchMenu` class is to be extended by rocket schematic classes so that they only need to register where their crafting slots are for the different schematics
  - Since it is not a crafting menu the `NasaWorkbenchSchematicMenu` gets its own separate class which handles holding onto the schematic the user gives it
- Created class hierarchy for the Screens of the device
  - The abstract class `AbstractNasaWorkbenchScreen` handles the shared logic of all the menu screens which is mostly the rendering and adding the nav buttons on the left
  - The `NasaWorkbenchSchematicScreen` also has the unlock button
- To communicate what recipes the user knows I decided to use advancements since they are held server side but will allow the user to look at what recipes they know and maybe in the future we can add some that are not strictly for making rockets but ones that will help guide the player
- Finally I added a new Recipe the `RocketeeringRecipe` which allows recipes to be encoded for each rocket much the same way that all other recipes are made
  - Because of #255 I can't set the recipe to output `galacticraft:rocket` or else the game crashes so I have left it as sand for now but it is a simple one line change once fixed
- I also added a few other things to make the bench work such as the rocket parts items

2023-01-25 02:53 UTC, supersimple33 commented
Ok seems this may need some changes didn't know of the modular rockets plan.

2023-01-25 03:18 UTC, AlphaMode commented
Creating rockets are still being planned out. We don't really plan on bringing back the nasa workbench, but this could work as a temporary solution until then...

2023-02-22 22:04 UTC, AlphaMode requested changes

2023-02-22 22:04 UTC, AlphaMode commented on src/main/java/dev/galacticraft/mod/Constant.java
> +        String NASA_WORKBENCH_SCREEN_HANDLER = "nasa_workbench_screen_handler";
The name should end with menu since we are following mojmap standards and not yarn standards anymore

2024-01-14 03:25 UTC, closed without merging