asteroid dimension
TeamGalacticraft/Galacticraft pull request #320
Opened 2024-05-22 12:14 UTC by maxryan008

Fixed some textures plus added asteroid dimension

2024-11-26 22:51 UTC, TheMCSpacePro commented
Rockets?

2025-02-12 11:50 UTC, Roelymole requested changes
I have looked over most things, but there is a lot, so my comments are by no means exhaustive. Hopefully this should be enough for you to get started on making some changes. I do think there is a fair amount of redundancy which you could work on reducing, so maybe the next time someone looks there won't be nearly so much to review.

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/api/perlin/FishyNoise.java
Does all of this noise generation need to be ported? If the vanilla noise generation can be used then it would be better and I suspect that it is possible now.

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/GalacticraftClient.java
I feel like a lot of this code should be in a different class such as `GCItems`.

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/client/gui/screen/ingame/OxygenSealerScreen.java
> +                graphics.drawString(this.font, Component.literal("Sealer Recheck: ").append(String.valueOf(sealCheckTime)), this.leftPos + 50, this.topPos + 50, ChatFormatting.YELLOW.getColor(), fals
Could you make this hardcoded text translatable. Also, I think it is best if you include the `%s` placeholder e.g. `"Sealer Recheck: %s"` so that the translations have more control over the formatting. Look at the machine status above for an example.

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +    public static final int FOOD_INPUT_SLOT_1 = 4;
It might simplify the code and reduce redundancy if you were to put these values into an array and iterate over them.

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +                            .filter((item, tag) -> item != null && item.components().has(DataComponents.FOOD) && !(item instanceof CannedFoodItem)),
You could define a helper function for this to avoid repeating the same thing 16 times. It would be much more maintainable this way.

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +        ItemGroupEvents.modifyEntriesEvent(ResourceKey.create(Registries.CREATIVE_MODE_TAB, Constant.id(Constant.Item.ITEM_GROUP_CANS))).register(entries -> {
Would registering all of the canned food before the creative mode tabs remove the need for this?

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/data/GCTranslationProvider.java
> +        this.item(GCItems.CANNED_FOOD, "Canned ");
Could you also use the `%s` placeholder here so that it is more translatable, as other languages might have a different word order.

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/data/GCTranslationProvider.java
> +        this.add(Ui.TOTAL_NUTRITION, "Total Nutrition: ");
Another `%s` placeholder would be good.

2025-02-12 11:50 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/events/GCEventHandlers.java
> +                    player.displayClientMessage(Component.literal("You cannot eat this here!").withColor(Color.RED.getRGB()), true);
Please make this hardcoded text translatable.

2025-02-12 11:50 UTC, Roelymole commented on src/main/resources/assets/galacticraft/textures/gui/food_canner_screen.png
These slot sprites will need to be removed from this texture and added in a different way. The style of them will need to be updated too.

2025-02-18 06:51 UTC, maxryan008 commented on src/main/java/dev/galacticraft/api/perlin/FishyNoise.java
Sure but when I did this I spent maybe 100+ hours trying to use vanilla generation to obtain a similar result and nothing seems to work. Perhaps with more time it could be rewritten but as far as I am aware the noise that I have used should be pretty much as efficient as possible so I wouldn't be too concerned about it...

2025-02-18 10:58 UTC, maxryan008 commented on src/main/resources/assets/galacticraft/textures/gui/food_canner_screen.png
Done

2025-02-18 11:56 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/events/GCEventHandlers.java
> +                    player.displayClientMessage(Component.literal("You cannot eat this here!").withColor(Color.RED.getRGB()), true);
Done and fixed up how the not eating code works

2025-02-18 11:57 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/GCTranslationProvider.java
> +        this.add(Ui.TOTAL_NUTRITION, "Total Nutrition: ");
Done

2025-02-18 11:59 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/GCTranslationProvider.java
> +        this.item(GCItems.CANNED_FOOD, "Canned ");
Done i think? changed to "Canned %s"

2025-02-18 12:13 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +        ItemGroupEvents.modifyEntriesEvent(ResourceKey.create(Registries.CREATIVE_MODE_TAB, Constant.id(Constant.Item.ITEM_GROUP_CANS))).register(entries -> {
Done. there is still a little leftover code in GCItems where i need to fix the colour of labels being programatically determined by the food contained within the item but it needs updating so leave it commented out for now

2025-02-18 12:43 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +                            .filter((item, tag) -> item != null && item.components().has(DataComponents.FOOD) && !(item instanceof CannedFoodItem)),
fixed. all 16 input slots are now one function with one parameter for the filter

2025-02-18 13:04 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/client/gui/screen/ingame/FoodCannerScreen.java
uh. can i fix this as i go along. if i go through every single file to fix brackets it will take me like a ridiculously long time so i can just fix the brackets every time i see one in the wrong format?

2025-02-18 13:06 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/GalacticraftClient.java
Already done

2025-02-18 13:20 UTC, maxryan008 commented on src/main/generated/data/galacticraft/advancement/recipes/building_blocks/raw_aluminum_block.json
fixed

2025-02-21 04:26 UTC, marcus8448 requested changes
This is an extremely large patch so I haven't gone over everything quite yet, but it's probably helpful to get this review in sooner than later (feel free to message me if you have any questions!)

Some general things:
* Might need to check files for the correct line endings
* Optimize imports should be run (via IntelliJ/your IDE)
* License headers need updating (`gradlew updateLicenses`)
* The curly brace placement should be consistent (placement on the same line)

I'm not super sold on the GC4 asteroid generation code - I can't say I understand how that code actually works, and the external save data system is slightly cursed.

2025-02-21 04:26 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/mixin/client/ClientTooltipMixin.java
> +    @Overwrite
`@Overwrite`s should be avoided as much as possible - I think fabric api's `TooltipComponentCallback` should do the same thing.

2025-02-21 04:26 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/mixin/client/FabricItemMixin.java
I think `DataComponents.FOOD` should be set on the canned food item, rather than overriding the component.

2025-02-21 04:26 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +    }
Tag names should be `PascalCase`

2025-02-21 04:26 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/machine/SealerManager.java
> +    public static final SealerManager INSTANCE = new SealerManager();
Would it be possible to attach this to a `Level` instead of a global state?

2025-02-21 12:48 UTC, Roelymole requested changes
I had already started this review before Marcus made his, but I have identified some different things and a possible solution to your Windows line ending problem with the `.gitattributes` and `.gitignore` files.

I can work with you on updating the worldgen rather than just porting GC4 code too.

2025-03-25 02:51 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/mixin/client/FabricItemMixin.java
> +            {
fixed brackets with reformat

2025-03-25 02:55 UTC, maxryan008 commented on src/main/java/dev/galacticraft/api/accessor/GearInventoryProvider.java
> +        return mask;
fixed

2025-03-25 02:56 UTC, maxryan008 commented on src/main/java/dev/galacticraft/impl/internal/fabric/GalacticraftAPI.java
> +import javax.swing.event.ChangeEvent;
ran optimize imports - fixed.

2025-03-25 02:56 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/Constant.java
> +    public static final String GCDATAFOLDER = "../galacticraft/";
removed GCDATAFOLDER Completely

2025-03-25 02:57 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/model/GCModelProvider.java
> +import static dev.galacticraft.machinelib.api.block.MachineBlock.ACTIVE;
ran optimize imports - fixed.

2025-03-25 02:57 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/GalacticraftClient.java
> +        nameOverride.add(new String[]{"air", "lime_dye"});
removed - fixed

2025-03-25 03:00 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/ClientCannedFoodTooltip.java
> +        }
fixed

2025-03-25 03:02 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/AirlockControllerBlockEntity.java
> +        return Component.literal(ownerName + "'s Air Lock Controller");
fixed. reverted back to old code. Don't know why I originally changed it?

2025-03-25 03:04 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +            ItemStack can = new ItemStack(CANNED_FOOD);
this should be a fix...
            ItemStack can = this.getDefaultInstance();

2025-03-25 03:08 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +    public static class TopNCollector<T> implements Collector<T, List<T>, String> {
removed custom collector and made a simple get top N amount from list function

2025-03-25 03:12 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +        }
fixed so appleskin passes in player as a value into the function

2025-03-25 03:18 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/GCItems.java
> +        for (Item item : BuiltInRegistries.ITEM)
it adds a food item for every singular food type. however after the world initialization there wont be any new foods being added to the game however new canned food types that contain multiple foods are still creatable during game play however so that the creative tab doesnt become overcrowded i chose to have multiple food containing cans not be added to the creative menu. as far as im aware this should work correctly where any single food can is added to creative menu on game initialization however after that it shouldnt add any new foods

2025-03-25 03:18 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/GCItems.java
> +//        });
ah yes that was a place holder however i will remove it

2025-03-25 03:20 UTC, maxryan008 commented on .gitattributes
fixed i believe?

2025-03-25 03:20 UTC, maxryan008 commented on .gitignore
fixed

2025-03-25 03:38 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +        }
there is still a Minecraft.getInstance().player inside of one of the client mixins but i believe because its in a client mixin it shouldnt crash?

2025-03-25 03:42 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +        }
Yeah, that should be fine. It's only a problem when client-only classes are referenced in common/server code.

2025-03-25 03:51 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/machine/SealerManager.java
> +    public static final SealerManager INSTANCE = new SealerManager();
each level now has its own manager

2025-03-25 04:02 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +    }
fixed pascal casae and made them a constant nbt tag aswell like progress is

2025-03-25 04:03 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/mixin/client/ClientTooltipMixin.java
> +    @Overwrite
yes that is fixed now it is in client code now with a tooltip component callback listener

2025-03-25 13:33 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/GCItems.java
> +    // === START BLOCKS ===
I didnt add any comments?

2025-03-25 13:36 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/mixin/client/FabricItemMixin.java
It has to be overridden in order to get correct food values. the canned food item is a singular java class however it represents many different can items ingame and they all have differant food values. the can item itself doesnt have a food value but rather the food inside it calculates its food value at runtime. if there is a better way of doing this im open to suggestions

2025-03-25 13:46 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/AirlockControllerBlockEntity.java
> +import static dev.galacticraft.mod.content.block.special.AirlockSealBlock.FACING;
fixed

2025-03-25 23:08 UTC, maxryan008 commented on .gitattributes
Done with result
Updated 0 paths from cec27c1d2

2025-03-25 23:09 UTC, maxryan008 commented on .gitignore
done with result
Updated 1 path from cec27c1d2

2025-03-25 23:11 UTC, maxryan008 commented on src/main/generated/data/galacticraft/advancement/recipes/building_blocks/raw_aluminum_block.json
because its in generated it should be auto generated when the datagen command is run. If its not then it means it doesnt have the code in datagen which needs to be added rather than adding it manually? or am i wrong?

2025-03-25 23:11 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/Constant.java
> +import net.minecraft.data.models.model.TextureSlot;
ran optimize imports

2025-03-25 23:11 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/client/gui/screen/ingame/FoodCannerScreen.java
fixed licensing and brackets

2025-03-25 23:13 UTC, maxryan008 commented on src/main/resources/galacticraft.mixins.json
> +    "client.FabricItemMixin",
fixed

2025-03-25 23:20 UTC, maxryan008 commented on src/main/resources/assets/galacticraft/textures/gui/food_canner_screen.png
fixed to match

2025-03-25 23:22 UTC, maxryan008 commented on src/main/resources/assets/galacticraft/models/block/air_lock_seal.json
> +    {   "from": [ 4, 0, 0 ],
fixed

2025-03-25 23:26 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/events/GCEventHandlers.java
> +                    player.displayClientMessage(Component.translatable("chat.cannotEatWithMask").withColor(Color.RED.getRGB()), true);
fixed

2025-03-25 23:26 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/events/GCEventHandlers.java
> +            player.displayClientMessage(Component.translatable("chat.cannotEatInNoAtmosphere").withColor(Color.RED.getRGB()), true);
done

2025-03-25 23:27 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/events/GCEventHandlers.java
> +import java.awt.*;
not anymore so i removed it

2025-03-26 00:27 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +            // 🔹 Recalculate and update the stored color
What is this symbol doing here?

2025-03-26 00:27 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +                // 🔹 Recalculate and store the new color inside the stack components
And another one here!

2025-03-26 00:27 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +            // 🔹 Recalculate and update the stored color
ah i used that because i was color coding my comments when debugging sorry...

2025-03-26 00:27 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +            // 🔹 Recalculate and update the stored color
i will remove them

2025-03-26 00:29 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +                // 🔹 Recalculate and store the new color inside the stack components
sorry i will remove it. when im working on code i put 🔹 in areas that i want to go back to quickly and use intellij's search all files feature to search for them

2025-03-27 00:06 UTC, Roelymole requested changes
It seems like for lots of the records you have put some of the arguments on to a new line, but the way you have done this doesn't seem to be very consistent and could do with being left the way it was or at least readdressed.

Once again, just porting the legacy code for the asteroid worldgen does not seem like the best approach and rewriting it from the ground up is probably required.

I have undoubtedly still missed things, with the sheer volume of changes, but 67 comments should be enough to keep you going for a little while.

2025-03-27 00:15 UTC, maxryan008 commented on src/main/java/dev/galacticraft/api/rocket/travelpredicate/ConfiguredTravelPredicate.java
> -public record ConfiguredTravelPredicate<C extends TravelPredicateConfig, T extends TravelPredicateType<C>>(C config, T type) {
Fixed

2025-03-27 00:17 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/client/resources/GCResourceReloadListener.java
@Override
    public void onResourceManagerReload(ResourceManager resourceManager) {
        var atlas = Minecraft.getInstance().getTextureAtlas(InventoryMenu.BLOCK_ATLAS);
        WireBakedModel.invalidate();
        WalkwayBakedModel.invalidate();
        WireWalkwayBakedModel.invalidate();
        PipeBakedModel.invalidate();
        FluidPipeWalkwayBakedModel.invalidate();
        BubbleEntityRenderer.bubbleModel = null;

        FluidRenderHandler oxygen = (view, pos, state) -> new TextureAtlasSprite[]{
                atlas.apply(Constant.Fluid.fluidId(Constant.Fluid.LIQUID_OXYGEN)),
                atlas.apply(Constant.id("block/fluid/oxygen")),
                atlas.apply(Constant.id("block/fluid/oxygen"))
        };

        FluidRenderHandlerRegistry.INSTANCE.register(GCFluids.LIQUID_OXYGEN, oxygen);
    }
    i believe that is all that is needed

2025-03-27 00:19 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +            tooltip.add(Component.translatable(Translations.Items.TOTAL_NUTRITION, Component.literal(String.valueOf(getTotalNutrition(stack)))).withColor(ChatFormatting.DARK_GRAY.getColor()));
whoops

2025-03-27 00:23 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/events/GCEventHandlers.java
> +            player.displayClientMessage(Component.translatable(Translations.Chat.CANNOT_EAT_IN_NO_ATMOSPHERE).withStyle(Constant.Text.RED_STYLE), true);
i reordered if statements so now it checks if item in hand is food first and then inside that the rest of the code runs. that way all options work properly

2025-03-27 00:30 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/events/GCEventHandlers.java
> +        boolean oxygenWorld = body.value().atmosphere().breathable();
fixed with if (body != null)

2025-03-27 00:50 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/GCBlockRegistry.java
fixed

2025-03-27 00:51 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/GCBlockRegistry.java
wait nevermind what do you mean more consistently
its currently formatted in the format block, slab, stairs, wall

2025-03-27 00:51 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/GCBlockRegistry.java
looks consistent to me?

2025-03-27 00:52 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/AirLockProtocol.java
nope removed it

2025-03-27 00:53 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/content/GCBlockRegistry.java
I mean you are starting a new line at different places, rather than after the wall each time for example.

2025-03-27 01:05 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenDecompressorBlockEntity.java
> +        if (StorageUtil.simulateExtract(tank, FluidVariant.of(Gases.OXYGEN), Long.MAX_VALUE, null) == 0)
done

2025-03-27 01:06 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/entity/Buggy.java
> +    ;
UH whoops

2025-03-27 01:07 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/entity/GCVehicle.java
i dont even remember editing GCVehicle code..... pretty sure that was the intellij formatting

2025-03-27 01:08 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/entity/orbital/lander/LanderEntity.java
> +                ;
Ok im genuinelly blaming alpha for this..... i didnt edit these. just formatted which has put it on a new line

2025-03-27 01:10 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/GCItems.java
> +    public static final CannedFoodItem EMPTY_CAN = ITEMS.register(Constant.Item.EMPTY_CAN, new CannedFoodItem(new Item.Properties().food(null).stacksTo(64)));
uh lol yes it does default

2025-03-27 01:17 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/GCBlockLootTableProvider.java
> +
fixed. sorted into alphabetical order for both the ore type and the dimension type... and grouped by ores

2025-03-27 01:18 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/world/gen/custom/AsteroidChunkGenerator.java
> +            for (AsteroidData asteroidIndex : new ArrayList<AsteroidData>(this.largeAsteroids)) {
This line seems to sometimes cause an issue. You might need to add extra checks beforehand.

```[00:59:14] [Server thread/INFO] (Minecraft) [Player733: Teleported to galacticraft:asteroid]
[00:59:15] [Render thread/INFO] (Minecraft) [System] [CHAT] Teleported to galacticraft:asteroid
[00:59:15] [Server thread/ERROR] (Minecraft) Error executing task on Chunk source main thread executor for galacticraft:asteroid
net.minecraft.ReportedException: Exception generating new chunk
	at knot/net.minecraft.server.level.ChunkMap.method_60445(ChunkMap.java:647) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:162) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:552) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:136) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:561) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:263) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:852) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:840) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:121) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:814) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:702) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/java.util.LinkedList.toArray(LinkedList.java:1064) ~[?:?]
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181) ~[?:?]
	at knot/dev.galacticraft.mod.world.gen.custom.AsteroidChunkGenerator.applyCarvers(AsteroidChunkGenerator.java:557) ~[main/:?]
	at knot/net.minecraft.world.level.chunk.status.ChunkStatusTasks.generateCarvers(ChunkStatusTasks.java:94) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.world.level.chunk.status.ChunkStep.apply(ChunkStep.java:33) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ChunkMap.applyStep(ChunkMap.java:632) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.GenerationChunkHolder.applyStep(GenerationChunkHolder.java:96) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ChunkGenerationTask.scheduleChunkInLayer(ChunkGenerationTask.java:143) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ChunkGenerationTask.scheduleLayer(ChunkGenerationTask.java:121) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ChunkGenerationTask.scheduleNextLayer(ChunkGenerationTask.java:74) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ChunkGenerationTask.runUntilWait(ChunkGenerationTask.java:59) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ChunkMap.method_60446(ChunkMap.java:665) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.method_17634(ChunkTaskPriorityQueueSorter.java:62) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at knot/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[minecraft-merged-96d760e3fc-1.21.1-loom.mappings.1_21_1.layered+hash.440304290-v2.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]```

2025-03-27 01:26 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/tag/GCBiomeTagProvider.java
> -                .addTag(GCTags.MOON);
nope

2025-03-27 01:34 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/tag/GCBlockTagProvider.java
> +                GCBlocks.TIN_ORE, GCBlocks.ASTEROID_SILICON_ORE,
alphabetically sorted now

2025-03-27 01:34 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/tag/GCBlockTagProvider.java
> +                        GCBlocks.ASTEROID_SILICON_ORE,
done

2025-03-27 01:40 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/tag/GCItemTagProvider.java
> +                GCBlocks.MARS_IRON_ORE.asItem(), GCBlocks.MARS_COPPER_ORE.asItem(), GCBlocks.MARS_TIN_ORE.asItem(),
fixed to be alphabetical and match GCBlockTagProvider ores registry

2025-03-27 01:40 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/mixin/client/SpriteContentAccessor.java
licenses regenerated

2025-03-27 01:47 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/world/biome/source/GCMultiNoiseBiomeSourceParameterLists.java
> +        context.register(ASTEROID, new MultiNoiseBiomeSourceParameterList(ASTEROID_PRESET, lookup));
when i start the asteroid biome pr i will delete all this anyway

2025-03-27 01:52 UTC, maxryan008 commented on src/main/resources/assets/galacticraft/blockstates/canned_food.json
fixed so its autogenerated

2025-03-27 01:59 UTC, maxryan008 commented on src/main/java/dev/galacticraft/impl/rocket/recipe/config/CenteredPatternedRocketPartRecipeConfig.java
I havent modified that file? only line endings....

2025-03-27 02:01 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/world/gen/custom/AsteroidChunkGenerator.java
> +            for (AsteroidData asteroidIndex : new ArrayList<AsteroidData>(this.largeAsteroids)) {
can i fix this when i make the new pr for asteroid dimension rewrite. no point fixing code thats going to be deleted?

2025-03-27 02:07 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +            setProgress(107);
custom encoding... specifically 107 is the final progress that the food canner checks for. sort of. it just works in that way... its hard to explain but from memory past 107 is when it renders the final move of the can

2025-03-27 02:08 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +    private int progress = 1;
nope... 0 is inactive i believe...

2025-03-27 05:04 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/client/model/CannedFoodBakedModel.java
> +                if (SpriteFinder.get(Minecraft.getInstance().getModelManager().getAtlas(TextureAtlas.LOCATION_BLOCKS)).find(quad).contents().name().toString().contains("canned_food_label_texture")) {
if (spriteFinder.find(quad).contents().name().toString().contains("canned_food_label_texture")) {

2025-03-27 05:06 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/client/model/CannedFoodBakedModel.java
> +
fixed?

2025-03-27 05:08 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +        return null;
fixed

2025-03-27 05:08 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/block/entity/machine/FoodCannerBlockEntity.java
> +    private int forthRowConsumed = 0;
fixed

2025-03-27 11:37 UTC, DMgaming100 commented on src/main/resources/assets/galacticraft/textures/block/vapor_spout.png
not needed, please remove

2025-03-27 12:01 UTC, Roelymole requested changes
Here is another batch of things that need adjusting.

For the records where you feel the line length is too long the `RocketData` class might be a good template to follow, otherwise just change it back to what it was before. I have commented "Can you adjust this." on each one I could find that you have modified.

2025-03-27 12:35 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +            tooltip.add(Component.translatable(Translations.Ui.TOTAL_NUTRITION, getTotalNutrition(stack)).withColor(ChatFormatting.DARK_GRAY.getColor()));
uh dark gray matches the f3 + h extra item info text.... which was the goal

2025-03-27 12:47 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/GCTranslationProvider.java
> -        this.add(Config.ELECTRIC_FURNACE_ENERGY_CONSUMPTION_RATE, "Electric Compressor Energy Consumption Rate/t");
ah fixed

2025-03-27 12:48 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/GCTranslationProvider.java
> -        this.add(Config.ELECTRIC_FURNACE_ENERGY_CONSUMPTION_RATE, "Electric Compressor Energy Consumption Rate/t");
never mind not fixed however nothing uses the arc furnace energy consumption rate. Config.ELECTRIC_ARC_FURNACE_ENERGY_CONSUMPTION_RATE doesnt even exist.... so i presume it uses the normal furnace consumption rate?

2025-03-27 12:49 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +            tooltip.add(Component.translatable(Translations.Ui.TOTAL_NUTRITION, getTotalNutrition(stack)).withColor(ChatFormatting.DARK_GRAY.getColor()));
I think the total nutrition information should be a bit more obvious than that personally.

2025-03-27 12:50 UTC, maxryan008 commented on src/main/java/dev/galacticraft/api/rocket/RocketData.java
i think its better now?

2025-03-27 12:52 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/data/GCTranslationProvider.java
> +        this.blockDesc(GCBlocks.FOOD_CANNER, "Food Canner is used to can up to %s food items into a can that can be eaten with a oxygen mask on.");
"Food Canner is used to compress up to %s edible items into a can that allows you to eat the food while wearing an oxygen mask."

2025-03-27 12:52 UTC, Roelymole commented on src/main/java/dev/galacticraft/mod/data/GCTranslationProvider.java
> -        this.add(Config.ELECTRIC_FURNACE_ENERGY_CONSUMPTION_RATE, "Electric Compressor Energy Consumption Rate/t");
Don't worry too much about it then.

2025-03-27 12:55 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/item/CannedFoodItem.java
> +            tooltip.add(Component.translatable(Translations.Ui.TOTAL_NUTRITION, getTotalNutrition(stack)).withColor(ChatFormatting.DARK_GRAY.getColor()));
Will make it gray then

2025-03-27 12:59 UTC, maxryan008 commented on src/main/java/dev/galacticraft/mod/content/GCBlocks.java
> +    public static final Block DENSE_ICE = BLOCKS.registerWithItem(Constant.Block.DENSE_ICE, new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLUE).instrument(NoteBlockInstrument.BASED
changed to ice. (matches ices texture closely)

2025-03-27 13:46 UTC, Roelymole commented on src/main/java/dev/galacticraft/impl/universe/celestialbody/config/DecorativePlanetConfig.java
> +        GasComposition atmosphere, float gravity,
`GasComposition atmosphere` and `float gravity` should probably be on separate lines too.

2025-03-27 13:48 UTC, maxryan008 commented on src/main/java/dev/galacticraft/impl/universe/celestialbody/config/DecorativePlanetConfig.java
> +        GasComposition atmosphere, float gravity,
fixed sorry i missed it

2025-03-27 14:55 UTC, Roelymole approved these changes

2025-03-27 19:48 UTC, merged