feat: better configuration
TeamGalacticraft/Galacticraft pull request #98
Opened 2021-04-03 18:59 UTC by marcus8448

Current changes:

- Rewrote the machine tab/panel screen
- Rewrote how side configurations are handled
- Rewrote how dynamic machine models are rendered (allowing for items to be dynamically rendered too!)
- Made a bunch of package names singular to follow fabric conventions
- Squashed bugs related to attributes
- More bugs

Todo:

- Handle and sync configuration panel clicks
- Use fewer magic numbers in the screen code
- Implement side config type setting
- Probably things I don't remember

2021-04-03 19:07 UTC, vos6434 commented
Always loved more more bugs 😆

2021-04-19 07:12 UTC, JoeZwet requested changes
some things still aren't renamed.

crash from trying to load moon village: https://pastebin.com/EiDJ28ZZ

2021-04-19 07:13 UTC, JoeZwet commented on src/main/java/dev/galacticraft/mod/item/OxygenTankItem.java
> +        return false;
it does not

2021-04-19 14:45 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/item/GalacticraftArmorMaterial.java
> +    ), // TODO: add actual functionality
That was there previously. I think #111 removes it.

2021-04-19 14:51 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/client/gui/widget/machine/OxygenTankWidget.java
> +//todo
Originally, I was going to implement the systems in a totally different way - I'll remove the file.

2021-04-19 14:57 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/Constants.java
> +        String FUEL_TIME = "FuelTime";
Resolved in ae90810f21a890433fe05db89270368109a1dff7.

2021-04-19 14:59 UTC, marcus8448 commented on src/main/java/dev/galacticraft/mod/compat/hook/ModMenuApiImpl.java
> +package dev.galacticraft.mod.compat.hook;
Changed to `dev.galacticraft.mod.compat.modmenu` in ae90810f21a890433fe05db89270368109a1dff7.

2021-04-21 08:53 UTC, JoeZwet approved these changes

2021-04-21 18:34 UTC, craftablescience requested changes
This is the only thing I noticed.

2021-04-21 18:34 UTC, craftablescience commented on src/main/java/dev/galacticraft/mod/Galacticraft.java
> +        GalacticraftServerPacketReceivers.register();
Would this be `GalacticraftServerPacketReceiver` to go with the singular naming scheme?

2021-04-21 18:39 UTC, craftablescience commented on src/main/java/dev/galacticraft/mod/Galacticraft.java
> +        GalacticraftServerPacketReceivers.register();
Actually now I see a few more plural things:
![image](https://user-images.githubusercontent.com/26600014/115604324-3d847700-a2af-11eb-8106-fc2d31eab99c.png)
![image](https://user-images.githubusercontent.com/26600014/115604345-45441b80-a2af-11eb-86e1-cfec6d69d0eb.png)
![image](https://user-images.githubusercontent.com/26600014/115604377-4b39fc80-a2af-11eb-966d-edadeb61c41f.png)
![image](https://user-images.githubusercontent.com/26600014/115604403-52f9a100-a2af-11eb-907e-bbd0f02046bd.png)
![image](https://user-images.githubusercontent.com/26600014/115604424-5ab94580-a2af-11eb-8aba-9e2fb61d90ae.png)

2021-04-22 20:53 UTC, craftablescience approved these changes
👍

2021-04-23 00:00 UTC, merged